name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v2
      id: procache
      with:
        path: |
          ~/__cache
        key: ${{ runner.os }}-procursus

    - name: Setup Procursus Bootstrap (install)
      if: steps.procache.outputs.cache-hit != 'true'
      run: |
        wget https://apt.procurs.us/bootstrap_darwin-amd64.tar.zst
        sudo gtar --preserve-permissions -xkf ./bootstrap_darwin-amd64.tar.zst -C /
        echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
        PATH=/opt/procursus/sbin:/opt/procursus/bin:$PATH sudo /opt/procursus/bin/apt update
        sudo /opt/procursus/bin/apt-get -V dist-upgrade -y || :
        sudo /opt/procursus/bin/apt-get -V dist-upgrade -y
        sudo /opt/procursus/bin/apt-get install ldid sed make -y
    - name: Setup environemnt
      run: |
        echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
        echo "PACKAGE_VERSION=$(cut -d v -f2 <<< $(git describe --tags))" >> $GITHUB_ENV

    - name: Setup Procursus Bootstrap (cache)
      if: steps.procache.outputs.cache-hit == 'true'
      run: |
        sudo mkdir -p ~/__cache/procursus/var/cache/apt/archives/partial ~/__cache/procursus/var/lib/apt/lists/partial
        sudo rsync -aP ~/__cache/procursus /opt
        sudo /opt/procursus/bin/apt-get update
        sudo /opt/procursus/bin/apt-get -V dist-upgrade -y
        sudo /opt/procursus/bin/apt-get -V dist-upgrade -y
    - name: Init Theos
      run: |
        git clone --recursive --depth=1 https://github.com/theos/theos.git ~/Theos
    
    - name: Compile
      run: |
        gmake -j$(sysctl -n hw.ncpu) package PACKAGE_VERSION=${{ env.PACKAGE_VERSION }} THEOS=~/Theos FINALPACKAGE=1 

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Successor CLI
        path: ./packages/com.dabezt.successorcli_${{ env.PACKAGE_VERSION }}_iphoneos-arm.deb

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      if: ${{ github.event_name == 'release' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./packages/com.dabezt.successorcli_${{ env.PACKAGE_VERSION }}_iphoneos-arm.deb
        asset_name: com.dabezt.successorcli_${{ env.PACKAGE_VERSION }}_iphoneos-arm.deb
        asset_content_type: application/octet-stream

    - name: Copy Procursus to Cache Location
      run: |
        sudo mkdir -p ~/__cache
        sudo rsync -aP /opt/procursus ~/__cache
        sudo rm -rf ~/__cache/procursus/var/cache/apt/archives/partial ~/__cache/procursus/var/lib/apt/lists/partial ~/__cache/procursus/Library/dpkg/triggers/Lock

